// ==========================================
// チャンピオン対策（カウンター）データ
// ==========================================
const COUNTER_DATA = {
    // --- TOP ---
    "Aatrox": ["Fiora", "Irelia", "Kled"],
    "Camille": ["Jax", "Fiora", "Darius"],
    "ChoGath": ["Fiora", "Gwen", "Kled"],
    "Darius": ["Teemo", "Vayne", "Quinn"],
    "DrMundo": ["Gwen", "Aatrox", "Kled"],
    "Fiora": ["Malphite", "Jax", "Pantheon"],
    "Gangplank": ["Riven", "Vladimir", "Quinn"],
    "Garen": ["Darius", "Camille", "Kayle"],
    "Gnar": ["Irelia", "Yasuo", "Wukong"],
    "Gragas": ["Garen", "Illaoi", "Darius"],
    "Gwen": ["Fiora", "Jax", "Riven"],
    "Illaoi": ["Mordekaiser", "Yorick", "Tryndamere"],
    "Irelia": ["Sett", "Volibear", "Jax"],
    "Jayce": ["Irelia", "Wukong", "Malphite"],
    "KSante": ["Gwen", "Fiora", "Garen"],
    "Kayle": ["Jax", "Irelia", "Camille"],
    "Kennen": ["Irelia", "Sylas", "Nasus"],
    "Kled": ["Fiora", "Jax", "Shen"],
    "Malphite": ["Sylas", "Mordekaiser", "Rumble"],
    "Mordekaiser": ["Olaf", "Fiora", "Vayne"],
    "Nasus": ["Darius", "Garen", "Illaoi"],
    "Olaf": ["Kled", "Illaoi", "Fiora"],
    "Ornn": ["Fiora", "Gwen", "Illaoi"],
    "Pantheon": ["Malphite", "Shen", "Ornn"],
    "Poppy": ["Darius", "Olaf", "Garen"],
    "Quinn": ["Malphite", "Irelia", "Camille"],
    "Renekton": ["Illaoi", "Garen", "Quinn"],
    "Riven": ["Renekton", "Poppy", "Kennen"],
    "Rumble": ["Aatrox", "Darius", "Irelia"],
    "Sett": ["Volibear", "Kled", "Malphite"],
    "Shen": ["Aatrox", "Darius", "Sett"],
    "Sion": ["Aatrox", "Darius", "Gwen"],
    "TahmKench": ["Vayne", "Gwen", "Heimerdinger"],
    "Teemo": ["Pantheon", "Rumble", "Aatrox"],
    "Tryndamere": ["Malphite", "TahmKench", "Nasus"],
    "Urgot": ["Rammus", "Shen", "Illaoi"],
    "Volibear": ["Illaoi", "Teemo", "Quinn"],
    "Wukong": ["Malphite", "Garen", "Darius"],
    "Yorick": ["Irelia", "Tryndamere", "Jax"],

    // --- JUNGLE ---
    "Amumu": ["KhaZix", "Shaco", "LeeSin"],
    "BelVeth": ["Rammus", "Poppy", "Amumu"],
    "Briar": ["Rammus", "Nocturne", "Amumu"],
    "Diana": ["Zac", "Nunu", "Rammus"],
    "Ekko": ["Rengar", "KhaZix", "Evelynn"],
    "Elise": ["Rengar", "KhaZix", "LeeSin"],
    "Evelynn": ["Rengar", "RekSai", "KhaZix"],
    "Fiddlesticks": ["XinZhao", "JarvanIV", "LeeSin"],
    "Graves": ["Zac", "Nunu", "Rammus"],
    "Hecarim": ["Nunu", "Rammus", "Sejuani"],
    "Ivern": ["Rengar", "KhaZix", "Nidalee"],
    "JarvanIV": ["XinZhao", "Graves", "Trundle"],
    "Karthus": ["KhaZix", "Rengar", "Evelynn"],
    "Kayn": ["Graves", "Kindred", "XinZhao"],
    "KhaZix": ["Rengar", "LeeSin", "Elise"],
    "Kindred": ["KhaZix", "LeeSin", "XinZhao"],
    "LeeSin": ["RekSai", "Elise", "Vi"],
    "Lillia": ["KhaZix", "Rengar", "JarvanIV"],
    "MasterYi": ["Rammus", "Udyr", "Jax"],
    "Nidalee": ["Rengar", "KhaZix", "Evelynn"],
    "Nocturne": ["Olaf", "Rammus", "Udyr"],
    "Nunu": ["KhaZix", "Rengar", "LeeSin"],
    "Rammus": ["Amumu", "Zac", "Sejuani"],
    "RekSai": ["KhaZix", "Evelynn", "Nidalee"],
    "Rengar": ["LeeSin", "XinZhao", "Udyr"],
    "Sejuani": ["Trundle", "Amumu", "Zac"],
    "Shaco": ["RekSai", "LeeSin", "KhaZix"],
    "Shyvana": ["XinZhao", "LeeSin", "KhaZix"],
    "Skarner": ["Olaf", "Morgana", "Trundle"],
    "Trundle": ["Teemo", "Jax", "Vayne"],
    "Udyr": ["Ashe", "Vayne", "Kite"],
    "Vi": ["Morgana", "Jax", "Ekko"],
    "Viego": ["Rammus", "XinZhao", "Nocturne"],
    "Warwick": ["Olaf", "Udyr", "Volibear"],
    "XinZhao": ["Jax", "Rammus", "Trundle"],
    "Zac": ["Vi", "JarvanIV", "LeeSin"],

    // --- MID ---
    "Ahri": ["Yasuo", "Zed", "Fizz"],
    "Akali": ["Vex", "Galio", "TwistedFate"],
    "Anivia": ["Kassadin", "Fizz", "Zed"],
    "Annie": ["Syndra", "Orianna", "Xerath"],
    "AurelionSol": ["Zed", "Fizz", "Katarina"],
    "Azir": ["Xerath", "VelKoz", "Zigss"],
    "Cassiopeia": ["Syndra", "Xerath", "VelKoz"],
    "Corki": ["Yasuo", "Zed", "Talon"],
    "Fizz": ["Lissandra", "Galio", "Kassadin"],
    "Galio": ["Lucian", "Tristana", "Vayne"],
    "Heimerdinger": ["Syndra", "Xerath", "Yasuo"],
    "Hwei": ["Zed", "Fizz", "Katarina"],
    "Kassadin": ["Talon", "Zed", "Lucian"],
    "Katarina": ["Kassadin", "Vex", "Galio"],
    "LeBlanc": ["Lissandra", "Malzahar", "Galio"],
    "Lissandra": ["Syndra", "Orianna", "Xerath"],
    "Lux": ["Yasuo", "Zed", "Fizz"],
    "Malzahar": ["Syndra", "Orianna", "Xerath"],
    "Naafiri": ["Vex", "Malzahar", "Lissandra"],
    "Neeko": ["Syndra", "Xerath", "VelKoz"],
    "Orianna": ["Syndra", "Zed", "AurelionSol"],
    "Qiyana": ["Vex", "Lissandra", "Malzahar"],
    "Ryze": ["Cassiopeia", "Anivia", "Xerath"],
    "Swain": ["Sylas", "Katarina", "Yone"],
    "Sylas": ["Cassiopeia", "Heimerdinger", "Vex"],
    "Syndra": ["Fizz", "Ekko", "Katarina"],
    "Talon": ["Lissandra", "Malzahar", "Vex"],
    "TwistedFate": ["Yasuo", "Zed", "Fizz"],
    "Veigar": ["Katarina", "Zed", "Fizz"],
    "VelKoz": ["Yasuo", "Zed", "Fizz"],
    "Vex": ["Syndra", "Xerath", "Orianna"],
    "Viktor": ["Syndra", "Xerath", "Ekko"],
    "Vladimir": ["Malzahar", "Anivia", "Kassadin"],
    "Xerath": ["Fizz", "Zed", "Katarina"],
    "Yasuo": ["Renekton", "Pantheon", "Lissandra"],
    "Yone": ["Renekton", "Pantheon", "Jax"],
    "Zed": ["Lissandra", "Malzahar", "Vladimir"],
    "Ziggs": ["Yasuo", "Zed", "Fizz"],
    "Zoe": ["Yasuo", "Zed", "Syndra"],

    // --- ADC ---
    "Aphelios": ["Ashe", "Twitch", "Draven"],
    "Ashe": ["Ezreal", "Sivir", "Lucian"],
    "Caitlyn": ["Sivir", "Ashe", "Jhin"],
    "Draven": ["Caitlyn", "Ashe", "MissFortune"],
    "Ezreal": ["Vayne", "Sivir", "Twitch"],
    "Jhin": ["Tristana", "Lucian", "Vayne"],
    "Jinx": ["Twitch", "Draven", "Lucian"],
    "Kaisa": ["Caitlyn", "Draven", "Ashe"],
    "Kalista": ["Ashe", "Draven", "Caitlyn"],
    "KogMaw": ["Lucian", "Draven", "Tristana"],
    "Lucian": ["Caitlyn", "Draven", "MissFortune"],
    "MissFortune": ["Draven", "Tristana", "Lucian"],
    "Nilah": ["Xayah", "Caitlyn", "Ashe"],
    "Samira": ["Nilah", "Senna", "Ashe"],
    "Sivir": ["Vayne", "Twitch", "Draven"],
    "Smolder": ["Draven", "Lucian", "Tristana"],
    "Tristana": ["Draven", "Caitlyn", "Xayah"],
    "Twitch": ["Draven", "Lucian", "Tristana"],
    "Varus": ["Ashe", "Sivir", "Jhin"],
    "Vayne": ["Caitlyn", "Draven", "Ashe"],
    "Xayah": ["Ashe", "Caitlyn", "MissFortune"],
    "Zeri": ["Twitch", "Draven", "Lucian"],

    // --- SUPPORT ---
    "Alistar": ["Morgana", "Janna", "Thresh"],
    "Bard": ["Engage", "Nautilus", "Leona"],
    "Braum": ["Morgana", "Zyra", "Karma"],
    "Blitzcrank": ["Morgana", "Leona", "Alistar"],
    "Janna": ["Sona", "Nami", "Soraka"],
    "Karma": ["Sona", "Soraka", "Yuumi"],
    "Leona": ["Morgana", "Janna", "Alistar"],
    "Lulu": ["Soraka", "Sona", "Senna"],
    "Milio": ["Nautilus", "Blitzcrank", "Pyke"],
    "Morgana": ["Karma", "Sona", "Zyra"],
    "Nami": ["Leona", "Nautilus", "Blitzcrank"],
    "Nautilus": ["Morgana", "Leona", "Braum"],
    "Pyke": ["Nautilus", "Leona", "Thresh"],
    "Rakan": ["Morgana", "Janna", "Thresh"],
    "Renata": ["Xerath", "Zyra", "Brand"],
    "Senna": ["Leona", "Nautilus", "Pyke"],
    "Seraphine": ["Leona", "Nautilus", "Pyke"],
    "Sona": ["Leona", "Nautilus", "Pyke"],
    "Soraka": ["Leona", "Nautilus", "Pyke"],
    "Taric": ["Morgana", "Zyra", "Brand"],
    "Thresh": ["Morgana", "Zyra", "Brand"],
    "Yuumi": ["Leona", "Nautilus", "Pyke"],
    "Zilean": ["Morgana", "Karma", "Lulu"],
    "Zyra": ["Leona", "Nautilus", "Pyke"]
};

// ==========================================
// チャンピオン基礎コンボデータ
// ==========================================
const COMBO_DATA = {
    // --- TOP ---
    "Aatrox": ["Q1 -> W -> Q2 -> E -> AA -> Q3 (フルコンボ)", "E -> Q1 (基本ハラス)"],
    "Camille": ["E1 -> E2 -> W -> Q1 -> AA -> Q2", "Q1 -> ミニオン -> E1 -> E2 -> Q2"],
    "ChoGath": ["Q -> W -> E -> AA -> R"],
    "Darius": ["E -> AA -> W -> Q (基本トレード)", "AA -> W -> Q (接近戦)"],
    "DrMundo": ["Q -> E -> AA -> W"],
    "Fiora": ["Q -> AA -> E1 -> Tiamat -> E2", "W (パリィ) -> Q -> AA"],
    "Gangplank": ["E1 -> E2 -> Q (基本樽)", "E1 -> E2 -> Q -> E3 (3連樽)"],
    "Garen": ["Q -> E -> W -> R (必殺コンボ)", "AA -> Q -> E (ショートトレード)"],
    "Gnar": ["Q -> AA -> W(スタック)", "E(ジャンプ) -> R(壁ドン) -> W -> Q"],
    "Gragas": ["W -> E -> Q -> R (バースト)"],
    "Gwen": ["Q(4スタック) -> E -> AA -> R"],
    "Illaoi": ["E(魂抜き) -> R -> W -> Q"],
    "Irelia": ["E1 -> R -> Q -> E2 -> Q -> AA -> Q", "E1 -> E2 -> Q -> AA -> Q"],
    "Jayce": ["Q -> E (キャノン) -> W -> R -> Q -> W -> AA", "Q -> E (遠距離ポーク)"],
    "KSante": ["Q3(打ち上げ) -> W(壁ドン) -> R -> Q -> AA"],
    "Kayle": ["Q -> AA -> E -> AA"],
    "Kennen": ["E -> R -> W -> Q (集団戦エンゲージ)"],
    "Kled": ["E -> Q -> W(4回AA) -> E"],
    "Malphite": ["Q -> E -> W -> AA", "R -> E -> Q -> W -> AA (ワンショット)"],
    "Mordekaiser": ["E -> Q -> AA (パッシブ発動)", "R -> E -> Q -> AA"],
    "Nasus": ["W -> E -> Q", "R -> W -> E -> Q"],
    "Olaf": ["Q -> AA -> E -> W -> AA -> Q"],
    "Ornn": ["Q -> E(壁ドン) -> W -> AA", "R1 -> R2 -> Q -> E -> W"],
    "Pantheon": ["W(強化) -> Q -> AA -> E", "R -> W(強化) -> E -> Q"],
    "Poppy": ["E(壁ドン) -> Q -> AA", "R(チャージ) -> 打ち上げ"],
    "Quinn": ["E -> AA -> Q -> AA"],
    "Renekton": ["E -> W -> Q -> E (ヒットアンドアウェイ)", "Flash -> W(強化) -> R -> Q -> E"],
    "Riven": ["Q -> AA -> Q -> AA -> Q -> AA (基本Qコンボ)", "E -> R -> Flash -> Q3 (エンゲージ)"],
    "Rumble": ["E -> E -> Q -> W (熱量管理)"],
    "Sett": ["E -> AA -> AA -> Q -> Q -> W", "R -> E -> W (集団戦エンゲージ)"],
    "Shen": ["E -> Q -> W -> AA", "R(味方) -> E -> Q"],
    "Sion": ["E -> Q(チャージ) -> W", "R -> Q(チャージ) -> E"],
    "TahmKench": ["Q -> W(ノックアップ) -> AA", "AA -> AA -> Q(スタン)"],
    "Teemo": ["AA -> Q -> AA (ハラス)"],
    "Tryndamere": ["E -> AA -> W -> AA", "R -> 殴り続ける"],
    "Urgot": ["Q -> E -> W (パッシブ発動させながら回る)"],
    "Volibear": ["Q -> E -> W -> AA", "R -> Q -> E -> W"],
    "Wukong": ["E -> Q -> AA -> W", "E -> R -> Q -> W -> R"],
    "Yorick": ["E -> W -> Q (グール召喚)"],

    // --- JUNGLE ---
    "Amumu": ["Q -> W -> E -> AA", "Q -> R -> W -> E"],
    "BelVeth": ["Q -> W -> Q -> E", "W -> Q -> E"],
    "Briar": ["W1 -> W2 -> Q -> E", "R -> W1 -> W2 -> Q"],
    "Diana": ["Q -> E -> W -> AA", "Q -> E -> R -> W -> AA"],
    "Ekko": ["W -> E -> Q -> AA (パッシブ発動)", "E -> Q -> AA"],
    "Elise": ["(ヒト)E -> Q -> W -> R -> (クモ)Q -> W -> AA", "(クモ)E -> Q -> W"],
    "Evelynn": ["W(チャージ) -> Q -> E -> R", "Q -> E -> Q -> Q"],
    "Fiddlesticks": ["R -> Q -> E -> W (集団戦)"],
    "Graves": ["AA -> E -> AA -> Q -> R", "W -> AA -> E -> AA"],
    "Hecarim": ["E(チャージ) -> Q -> AA -> W", "R -> E -> Q -> W"],
    "Ivern": ["Q -> E -> AA", "R(デイジー) -> Q -> E(デイジーにつける)"],
    "JarvanIV": ["E -> Q -> AA -> W -> R", "R -> E -> Q (確実な逃げ潰し)"],
    "Karthus": ["W -> Q -> Q -> E", "R (フィニッシュ)"],
    "Kayn": ["Q -> AA -> W", "W -> Q -> R (青ケインバースト)"],
    "KhaZix": ["W -> E -> Q -> AA", "E -> Q -> W -> AA -> R"],
    "Kindred": ["W -> Q -> E -> AA", "Q -> W -> AA -> E"],
    "LeeSin": ["Q1 -> R -> Flash -> Q2 (インセク)", "Q1 -> Q2 -> Ward -> W -> R"],
    "Lillia": ["E -> Q -> W", "Q -> R(睡眠) -> W(中心)"],
    "MasterYi": ["Q -> E -> AA -> W(AAキャンセル) -> AA", "R -> Q -> E -> AA"],
    "Nidalee": ["Q(槍) -> R -> W(ジャンプ) -> E -> Q", "AA -> R -> W -> E -> Q"],
    "Nocturne": ["Q -> E -> W -> AA", "R -> Q -> E -> W"],
    "Nunu": ["W(雪玉) -> E -> Q -> R", "E -> Q -> R"],
    "Rammus": ["Q -> W -> E -> R", "Q -> Flash -> E"],
    "RekSai": ["(潜行)Q -> W(ノックアップ) -> Q -> E -> R"],
    "Rengar": ["R -> Q(ジャンプ) -> E -> W -> 強化Q"],
    "Sejuani": ["Q -> W -> AA -> E -> R", "R -> Q -> W -> E"],
    "Shaco": ["Q -> W(箱) -> 背後AA -> E", "R -> Q -> 背後AA"],
    "Shyvana": ["E -> W -> Q -> AA", "R -> E -> W -> Q"],
    "Skarner": ["E -> R -> 引き寄せ -> Q", "W -> E -> AA"],
    "Trundle": ["E(柱) -> W -> Q -> AA -> R"],
    "Udyr": ["E(スタン) -> Q(覚醒) -> AA", "E -> R(覚醒) -> W"],
    "Vi": ["Q(チャージ) -> AA -> E -> R", "R -> Q -> AA -> E"],
    "Viego": ["W -> AA -> Q -> AA -> R", "E -> W(チャージ) -> Q -> AA"],
    "Warwick": ["W -> Q(長押し) -> E -> R", "R -> Q -> E"],
    "XinZhao": ["E -> AA -> Q1 -> Q2 -> Q3 -> W", "W -> E -> AA -> Q"],
    "Zac": ["E -> W -> Q -> ミニオンAA -> R", "Q -> 敵AA -> 敵AA -> E -> W -> R"],

    // --- MID ---
    "Ahri": ["E -> Q -> W -> AA", "R -> E -> Q -> W -> R"],
    "Akali": ["R1 -> E1 -> E2 -> AA -> Q -> W -> R2", "Q -> W -> AA -> Q"],
    "Anivia": ["Q -> Q(起爆) -> E", "R -> W(壁) -> Q -> E"],
    "Annie": ["Flash -> R(クマ) -> Q -> W", "Q(スタック溜め) -> W -> R"],
    "AurelionSol": ["E -> Q(長押し)", "R -> E -> Q -> W(追いかけ)"],
    "Azir": ["W -> Q -> AA", "W -> E -> Q -> R (シュリーマシャッフル)"],
    "Cassiopeia": ["Q -> E -> E -> E", "W -> Q -> E -> R"],
    "Corki": ["Q -> E -> R -> AA", "W(パッケージ) -> Q -> E -> R"],
    "Fizz": ["R -> E -> W -> Q", "Q -> AA -> W -> E(離脱)"],
    "Galio": ["E -> W(タメ) -> Q -> AA", "R -> W -> E -> Q"],
    "Heimerdinger": ["E(スタン) -> W -> Q(砲台レーザー)", "RE(強化スタン) -> W"],
    "Hwei": ["Q -> Q (ポーク)", "E -> W -> Q -> Q -> R"],
    "Kassadin": ["R -> E -> W -> Q", "R -> Flash -> E -> W -> Q"],
    "Katarina": ["E -> W -> Q -> E -> R", "Q -> E -> W -> R"],
    "LeBlanc": ["W -> Q -> R -> E (バースト)", "Q -> W -> AA -> W(戻り)"],
    "Lissandra": ["E1 -> E2 -> W -> Q -> R", "R(自分) -> W -> Q"],
    "Lux": ["Q -> E -> R -> E(起爆) -> AA", "E -> E(起爆) -> Q -> R"],
    "Malzahar": ["E -> W -> Q -> R", "Q -> E -> W -> R"],
    "Naafiri": ["W -> E -> Q1 -> Q2", "R -> W -> Q1 -> E -> Q2"],
    "Neeko": ["E -> Q -> W(強化AA)", "R(チャージ中にFlash) -> E -> Q"],
    "Orianna": ["Q -> W -> AA -> E", "Q -> R -> W -> E"],
    "Qiyana": ["Q(水) -> W(岩) -> E -> Q", "E -> R -> Q -> W -> Q"],
    "Ryze": ["Q -> E -> Q -> W -> Q", "E -> W -> Q -> E -> Q"],
    "Swain": ["E -> 引き寄せ -> W -> Q", "R -> E -> W -> Q"],
    "Sylas": ["E1 -> E2 -> AA -> Q -> AA -> W -> AA", "W -> AA -> E1 -> E2 -> Q"],
    "Syndra": ["Q -> E (スタン) -> W -> Q -> R", "Q -> W -> Q -> E"],
    "Talon": ["W -> Q -> AA -> R", "R -> W -> Q -> AA"],
    "TwistedFate": ["W(黄) -> Q -> AA", "R -> W(黄) -> Q"],
    "Veigar": ["E(檻) -> W -> Q -> R", "Q -> R (フィニッシュ)"],
    "VelKoz": ["Q -> Q(起爆) -> W -> E -> R", "E -> W -> Q -> R"],
    "Vex": ["R1 -> R2 -> W(フィアー) -> E -> Q", "E -> Q -> W(フィアー)"],
    "Viktor": ["E -> Q -> AA", "W -> R -> E -> Q"],
    "Vladimir": ["Q(強化) -> E -> W(潜り) -> R", "R -> E(溜め) -> Q"],
    "Xerath": ["E -> W -> Q", "R -> R -> R"],
    "Yasuo": ["E -> Q -> Flash (EQフラッシュ)", "Q3 -> R -> Ignite", "AA -> Q -> AA -> E"],
    "Yone": ["E -> Q3 -> W -> AA -> R -> Q -> E戻り", "Q3 -> Flash -> R"],
    "Zed": ["W -> E -> Q -> W (基本ハラス)", "R -> W -> E -> Q -> AA -> R (フルコンボ)"],
    "Ziggs": ["E -> W -> Q -> R", "W(自分飛ばし) -> Q -> E"],
    "Zoe": ["E -> Q1(後ろ) -> Q2(前) -> R", "R -> E -> Q1 -> Q2"],

    // --- ADC ---
    "Aphelios": ["(武器依存) 白赤: 接近してAA連打 -> 赤Q", "紫: 遠距離AA -> Q(スネア)"],
    "Ashe": ["W -> AA -> Q -> AA", "R -> W -> AA -> Q"],
    "Caitlyn": ["W(罠) -> Q -> 強化AA -> E -> 強化AA", "E -> Q -> 強化AA"],
    "Draven": ["W -> AA -> Q(キャッチ) -> W -> AA", "E -> R -> AA"],
    "Ezreal": ["W -> Q -> AA", "W -> E -> AA -> Q -> R"],
    "Jhin": ["AA -> Q -> AA", "W(スネア) -> AA -> Q -> 4th AA"],
    "Jinx": ["AA -> W -> E (罠ハメ)", "E -> AA -> W -> R"],
    "Kaisa": ["AA -> Q -> AA -> W", "W -> R -> AA -> Q -> AA"],
    "Kalista": ["AA(跳躍) -> AA(跳躍) -> E", "Q -> AA(跳躍) -> E"],
    "KogMaw": ["W -> AA -> AA -> Q -> R", "E -> W -> AA連打"],
    "Lucian": ["E -> AA -> Q -> AA -> W -> AA", "W -> AA -> E -> AA -> Q -> AA"],
    "MissFortune": ["AA -> Q(後方バウンド) -> AA", "E -> R"],
    "Nilah": ["E -> Q -> AA -> AA -> W", "R -> E -> Q -> AA"],
    "Samira": ["AA -> Q -> AA -> E -> W -> R (Sランクコンボ)"],
    "Sivir": ["AA -> W -> Q -> AA", "R -> AA -> W -> Q"],
    "Smolder": ["Q -> W -> AA", "E -> Q -> W -> R"],
    "Tristana": ["E -> Q -> AA -> AA -> W -> AA(起爆)", "W -> E(空中) -> R"],
    "Twitch": ["Q(ステルス) -> W -> R -> AA連打 -> E", "W -> AA -> E"],
    "Varus": ["E -> AA -> AA -> AA -> WQ", "R -> WQ -> E"],
    "Vayne": ["AA -> Q -> AA -> E (壁ドン)", "R -> Q -> AA -> E -> AA"],
    "Xayah": ["Q -> AA -> E (即スネア)", "W -> AA連打 -> R -> E"],
    "Zeri": ["Q -> Q -> W(壁越し) -> E -> Q", "R -> Q連打 -> E"],

    // --- SUPPORT ---
    "Alistar": ["W -> Q (WQコンボ)", "Flash -> Q -> W(押し出し)"],
    "Bard": ["Q(壁スタン) -> 強化AA", "R(敵) -> Q(スタン準備)"],
    "Braum": ["Q -> W(味方) -> E", "R -> Q -> AA(スタック)"],
    "Blitzcrank": ["Q -> E -> R", "W(接近) -> E(打ち上げ) -> Q(逃げ先)"],
    "Janna": ["Q(タメ) -> W -> E(味方)", "R(弾き飛ばし) -> Q"],
    "Karma": ["R -> Q (強化Qハラス)", "E -> W -> R -> Q (スネアコンボ)"],
    "Leona": ["E -> Q -> W -> R", "R -> E -> Q -> W"],
    "Lulu": ["E(敵) -> Q -> AA", "W(味方) -> E(味方) -> R"],
    "Milio": ["Q(弾き) -> W -> E(味方)", "R(全体回復・クレンズ)"],
    "Morgana": ["Q -> W -> R -> Zhonya", "E(ブラックシールド) -> R"],
    "Nami": ["E(味方/自分) -> W -> Q(泡)", "R -> Q -> W"],
    "Nautilus": ["Q -> AA(パッシブ) -> W -> E -> R", "R -> Q -> AA -> W -> E"],
    "Pyke": ["Q(チャージ) -> E -> AA -> R", "E -> Flash -> Q -> R"],
    "Rakan": ["R -> W(打ち上げ) -> E(味方帰還)", "W -> Q -> E(味方)"],
    "Renata": ["Q1 -> Q2(投げる) -> E", "R -> W(味方)"],
    "Senna": ["AA -> Q -> AA", "W -> R -> E"],
    "Seraphine": ["E(スロウ) -> Q -> W", "R -> E -> Q"],
    "Sona": ["Q -> 強化AA(青)", "R -> Q -> 強化AA"],
    "Soraka": ["Q -> W(味方回復)", "E(沈黙) -> Q"],
    "Taric": ["E(スタン) -> W -> Q -> AA", "R -> E -> W"],
    "Thresh": ["Q1 -> Q2 -> E -> R", "E(手前引き) -> Q -> R"],
    "Yuumi": ["W(乗る) -> Q -> E(回復)", "R -> Q"],
    "Zilean": ["Q -> W -> Q (ダブルボム)", "E(味方/敵) -> Q -> W -> Q"],
    "Zyra": ["E -> W(種) -> Q -> W(種) -> R", "Q -> W -> E"]
};
